# Generated by Django 4.2.4 on 2023-09-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('trade_code', models.CharField(max_length=20)),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('open', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
