# Generated by Django 4.2.4 on 2023-09-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.CharField(max_length=20),
        ),
    ]
