# Generated by Django 4.2.4 on 2023-09-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_stockdata_close_alter_stockdata_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='date',
        ),
    ]
